### ISSUE TITLE
user can turn their car

### ISSUE THREAD

**Issue by Han-Zhang-Code** [Han-Zhang-Code/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] declare turn classes in css using `transform:rotate()`
- [x] add `transition:transform` for each function for animation 
- [x] use 'keydown' method for addEventListener and querySelector for the car image
- [x] when user press the arrows on keyboard, change the class name accordingly
