### ISSUE TITLE
user can start the car

### ISSUE THREAD

**Issue by Han-Zhang-Code** [Han-Zhang-Code/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] make the car image position absolute
- [x] make background position relative 
- [x] declare new variable x and y and initialize to 0
- [x] if the user press the space, change the translate value in transform property for the car by using `document.getElementById('id').style.transform` method so that the car can move horizontally 
- [x] use `setInterval` method to let the car keeps moving at 16 millisecond per pixel
