### ISSUE TITLE
user can stop the car

### ISSUE THREAD

**Issue by Han-Zhang-Code** [Han-Zhang-Code/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] set a boolean variable equal to `false`
- [x] change the boolean variable to `true` when user start the car (press the space)
- [x] if the boolean variable is `true` that means the car already start, use that as the condition and inside the condition code block, stop the car by calling `clearInterval()` and reset the boolean variable to `false`
